### ISSUE TITLE
Add hyperlinkID to hero json file

### ISSUE THREAD

**Issue by Zemill** [heroespatchnotes/heroes-talents#107]
The new talent build copy process in patch 2.50 appears to use the hyperlinkID.  Currently the json files are missing that value.

**Comment by MGatner** [comment]
We have `hyperlinkID` in its lower-case version as the "shortName". Since case is a one-way conversion I would be in favor of adding `hyperlinkID` and deprecating `shortName` so we could drop it a few patches down the road, since developers could always re-create it with `lower($hyperlinkID)`. @stuaroo thoughts?

**Comment by stuaroo** [comment]
I like that idea, let's go that direction.
