### ISSUE TITLE
Hero icon sizing

### ISSUE THREAD

**Issue by MGatner** [heroespatchnotes/heroes-talents#21]
Mal'Ganis and Zul'jin both have portrait icons that are more than double the standard. Those two are consistent with the version I extract (HeroesDataParser) so I assume you do some compressing. Could you elaborate on that re-sizing process? And then one of us can address the two specific icons.

**Comment by stuaroo** [comment]
I'm not sure what you mean by this.  For hero images, I've always extracted the target portrait and then converted from .dds to .png resulting in a 92x93 image.  The only exceptions should be Alexstrasza and Hanzo which output at 92x92 and have been adjusted to also be 92x93 for consistency.

Are you maybe looking at a different portrait icon?

**Comment by MGatner** [comment]
I'm noticing that in a fresh clone of heroes-talents the files in images/heroes are all 6-9Kb, except for Mal'Ganis and Zul'jin which are closer to 20Kb - a notable difference. When I use HeroesDataParser and do an extract of the game data the resulting hero portraits (e.g. ui_targetportrait_hero_whitemane.png) are all closer to 20Kb. This led me to believe you were doing some resolution change, or stripping color profiles, or something to reduce the size.
A demonstration:
`diff HeroesDataParser/images/portraits/ui_targetportrait_hero_whitemane.png /Library/Git/heroes-talents/images/heroes/whitemane.png 
Binary files HeroesDataParser/images/portraits/ui_targetportrait_hero_whitemane.png and /Library/Git/heroes-talents/images/heroes/whitemane.png differ`

Versus no diff from Mal'Ganis:
`diff HeroesDataParser/images/portraits/ui_targetportrait_hero_malganis.png /Library/Git/heroes-talents/images/heroes/malganis.png`

**Comment by stuaroo** [comment]
Alrighty, after digging through the commits from a year ago when images were first added, it appears that all hero images were pulled in from the Heroes Patch Notes site originally.  I do take the extra step of compressing images for the website (using [TinyPNG](https://tinypng.com/) generally), which now makes more sense why there are so many differences between the raw image output of HeroesDataParser and the images in the repo.  Since adding new images for heroes-talents is usually the last step I do, I almost always have the compressed version of the file on hand, but it looks like a couple of them went in uncompressed.

Does it make sense to continue using compressed images though?  Or in the interest of future automation should they be switched to the raw output?

**Comment by MGatner** [comment]
Now with the idea of including the raw HeroesDataParser output I like keeping the compressed version in images/heroes. I use them on the website because 10k isn't that big a difference but 10k * 84 every time you load is respectable.
Talent icons appear to have been resized for the repo - do you use TinyPNG for that as well, or something else?

**Comment by stuaroo** [comment]
I've been using the [Image Magick command line tool](https://www.imagemagick.org/) to convert all .dds to .png, and also use it for the resize to 64x64 on talent icons.  Not sure why 64x64 was the chosen size, but that's what everything was on the first pull request to add them and I've just stuck to that size ever since.  

It may be worth having a conversation in the future if we want bigger/different sizes.

**Comment by MGatner** [comment]
HeroesDataParser conveniently spits out PNGs already (koliva

**Comment by MGatner** [comment]
Didn’t mean to close yet!

**Comment by MGatner** [comment]
I will add image compression to 64x64 to the automated process. Do you want images/talents to be the current set of all talent/ability icons? or do you want to keep around icons that are no longer in use?

**Comment by stuaroo** [comment]
I think it makes sense to have images/talents be the current set of icons, and it's a good way to keep the repo 'cleaner' going forward.

**Comment by MGatner** [comment]
Fixed by https://github.com/heroespatchnotes/heroes-talents/pull/28
