### ISSUE TITLE
Document data extraction process

### ISSUE THREAD

**Issue by poma** [heroespatchnotes/heroes-talents#5]
Looks like quite a few developers might be interested in extending and automating hero data extraction. If we document how we currently get the data presented in this repo, others might be able to contribute and improve this process.

**Comment by mjibson** [comment]
I've just open sourced my talent extraction code. https://github.com/mjibson/hots.dog/tree/master/casc. I plan on maintaining that going forward, and am not opposed to making a separate repo that's just for the extraction, including data, so we can all get it from the same place.

**Comment by stuaroo** [comment]
@mjibson I'm excited to give your code a try; any tips for first-time setup of a Go environment?

**Comment by mjibson** [comment]
https://golang.org/dl/ has packaged go distributions. In addition to Go, though, this project requires https://github.com/nydus/storm-extract and imagemagick. Since there's interest maybe I'll work on extracting it to its own repo with documentation. If you can get those things installed, though, make a symlink called `hots` to your hots program files directory, run `bash extract.sh` then `go get -d; go run extract.go xml.go`. And it'll make a `../talents.go` file with the data. This will improve once it is its own project.

**Comment by mjibson** [comment]
For the short term, you can also just get the data directly from the generated file at https://github.com/mjibson/hots.dog/blob/master/talents.go

**Comment by MGatner** [comment]
https://github.com/koliva8245/HeroesDataParser is doing the extraction very well, and up-to-date, and  @koliva8245 is very accessible. @stuaroo recommended this for leveraging updates going forward and I'm working on a mostly-automated process for that pipeline.

**Comment by MGatner** [comment]
I have mostly-automated updates in place! Here's the rough process:
* IFTTT hits us with a notification (via Pushover) whenever there's an update to https://github.com/Blizzard/heroprotocol
* Whoever gets to it first launches Battle.net and patches HotS, then runs extract.sh
* extract.sh checks all dependencies and repos for updates then calls HeroesDataParser with the following:

`"$parserDir/HeroesData" --description 3 --storagePath "$hotsDir" --extract all --json --outputDirectory "$selfDir/HeroesDataParser" --heroWarnings --localization all`

* extract.sh commits extracted data to our internal repo and notifies the server
* server pulls extracted game data and runs GameData->import (to update the database) then GameData->export (to create heroes-talent heroes JSON files)
* server pulls, updates, and commits https://github.com/MGatner/heroes-talents with HeroesDataParser raw output and the new JSON files
* server notifies me for review and pull request to heroes-talents

It's not pretty nor fully automated but since we don't have a Windows server running all the time I couldn't get around the need for the local/server split. I think we could have data up within 10 minutes of a patch, depending on team response time to the initial notification and my daytime availability.
Open to suggestions and feedback!

**Comment by stuaroo** [comment]
The process sounds good to me, do you think we'll be ready to try it on the next patch?  The only suggestion that came to mind is you may want to consider an additional IFTTT for new patches; from my own experience watching the heroprotocol repo, it seems like the new version commit lags behind the actual patch by minutes to hours (while the PTR commit can be hours or days later).  I've started monitoring the [feed from Blizztrack](https://blizztrack.com/patch_notes/heroes_of_the_storm/latest) as well, since I believe they scrape the launcher for patch notes and often they'll have a new patch up before I see a heroprotocol commit.  Just an idea if you're looking for patch data as quickly as possible!

**Comment by MGatner** [comment]
How updated is that observation? I’ve only had IFTTT watching the repo for 3 weeks, but so far I’ve been getting the heroprotocol notice even before the patch goes live! If it isn’t consistent and lags sometime I’m definitely interested in an alternate/additional source. 

I think we’ll be all set for Orphea live patch. Definitely a few tweaks to the actual export format but I feel good about the process and overall result, if you are.

I’m curious how @poma and @mjibson feel about this since it was their issue originally. I’m not even sure if you’re actively using this repo?

**Comment by stuaroo** [comment]
That's a good point, I'd been burned enough times by watching only the heroprotocol repo that I started using other resources and haven't been actively tracking it recently.  It very well could be a lot more consistent these days.

I'm also feeling good about the process/output, so let's see how it goes for Orphea!

**Comment by MGatner** [comment]
There's a fair amount of additional conversant (mostly between stuaroo and myself) but I added the general automation process to the wiki: https://github.com/heroespatchnotes/heroes-talents/wiki/Extraction-Process
Closing this issue 14 months later
