### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by arranf** [heroespatchnotes/heroes-talents#9]
The following blaze icons are missing
```
storm_ui_icon_blaze_stim_2.png
storm_ui_icon_blaze_stim_1.png
storm_ui_icon_blaze_stim_3.png
storm_ui_icon_blaze_new_habits.png
storm_ui_icon_blaze_flame.png
storm_ui_icon_blaze_oil.png
storm_ui_icon_blaze_oil.png
storm_ui_icon_blaze_pyromania.png
storm_ui_icon_blaze_flame.png
storm_ui_icon_blaze_oil.png
storm_ui_icon_blaze_bunker.png
storm_ui_icon_blaze_combustion.png
storm_ui_icon_blaze_flame.png
storm_ui_icon_blaze_oil.png
storm_ui_icon_blaze_jet.png
storm_ui_icon_blaze_jet.png
storm_ui_icon_blaze_pyromania.png
storm_ui_icon_blaze_vanadium_plating.png
storm_ui_icon_blaze_bunker.png
storm_ui_icon_blaze_combustion.png
```

In addition many of Malfurions talent's have new images. Is there a repeatable script you use to extract these images? Or should I create one myself and contribute the images back?

**Comment by stuaroo** [comment]
D'oh, the last commit had `firebat` images instead of `blaze`!

I haven't created a script yet for images; so far it's been a process of extract with Casc Viewer and resize/convert with Image Magick.  I am going to work on a basic validate script to make sure images referenced in the JSON exist in the project.  

Always open to contributions though, feel free to pull request if you find anything else missing or wrong!

**Comment by arranf** [comment]
@stuaroo I'll see if I can produce something. I know there is a good basis for this here: https://github.com/mjibson/hots.dog/tree/master/casc
